spring:
  security:
    user:
      name: hongcd
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false