spring:
  application:
    name: eureka-server
  security:
    user:
      name: hongcd
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false